spring.application.name=teamsync

# Datenbank-Verbindung (Nutzt Variablen aus .env, Fallback auf lokale Postgres)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/teamsync_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1234}

# JPA / Hibernate Einstellungen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

# JWT Einstellungen (Variablen aus .env)
teamsync.jwt.secret=${JWT_SECRET:MeinSuperGeheimesPasswortDasNiemandErratenKann1234567890}
teamsync.jwt.expirationMs=${JWT_EXPIRATION:43200000}